defaults:
  - _self_
  - dataset: cora # Can be: aids actor planetoid karate attributed webkb enzymes protein 
  - model: gcn # Can be: gcn gat cheb
  - optimizer: adam
  - general: general_default
  - task: link # Can be: node or graph
  - explainer: combinex # Can be: gnnexplainer | cf-gnn | combinex | ego | random | random-feat
  - trainer: trainer
  - logger: wandb
  - scheduler: scheduler


verbose: False
random_num_epochs: 500
device: cuda
workers: 1
path: ""
seed: 1
run_mode: run
figure: False
# Project name on wandb
project: COMBINEX
name: test

# Eventual timeout in seconds to kill the process
timeout: 500

# Number of agents to carry out the simulation
num_agents: 1
test_size: 0.2
max_samples: 100